#include <omp.h>
#include <windows.h>
#include <tchar.h>
#include <string>
#include <cstdint>
#include <stdio.h>
#include <psapi.h>
#include <processthreadsapi.h>
#include <sysinfoapi.h>
#include <tlhelp32.h>
